version: "3"

services:
    grafana:
        image: grafana/grafana-oss
        container_name: grafana
        restart: unless-stopped
        ports:
            - "3000:3000"
        volumes:
            - grafana_data:/var/lib/grafana
    loki:
        image: grafana/loki:2.9.0
        container_name: grafana-loki
        command: -config.file=/etc/loki/local-config.yaml
        volumes:
            - ./loki-config.yaml:/etc/loki/local-config.yaml
        ports:
            - "3100:3100"
    promtail:
        image: grafana/promtail:2.9.0
        container_name: promtail
        volumes:
            - ./logs:/var/log/nginx
            - ./promtail-config.yaml:/etc/promtail/config.yml
        command: -config.file=/etc/promtail/config.yml
    app:
        build:
            context: app
        ports:
            - "5000"
    nginx:
        image: nginx:latest
        volumes:
            - ./logs:/var/log/nginx
            - "./nginx.conf:/etc/nginx/nginx.conf"
        depends_on:
            - app
        ports:
            - "8080:80"
volumes:
  grafana_data: {}
networks:
  grafana: